[colors]
draw_bold_text_with_bright_colors = true

[colors.dim]
black   = "0x000000"
red     = "0x8c3336"
green   = "0x7a8530"
yellow  = "0x97822e"
blue    = "0x506d8f"
magenta = "0x80638e"
cyan    = "0x497e7a"
white   = "0x9a9a9a"

[colors.normal]
black   = "0x1c1f24"
red     = "0xff6c6b"
green   = "0x98be65"
yellow  = "0xda8548"
blue    = "0x3071db"
magenta = "0x8a549a"
cyan    = "0x5699af"
white   = "0xbbc2cf"

[colors.bright]
black   = "0x5b6268"
red     = "0xff3c3b"
green   = "0xb6d193"
yellow  = "0xecbe7b"
blue    = "0x51afef"
magenta = "0xc678dd"
cyan    = "0x46d9ff"
white   = "0xffffff"
